name: Local ERPNext Deploy

on:
  push:
    branches: 
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:    

jobs:
  deploy-local:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # Skip Python setup action - use system Python instead
    - name: Use system Python
      run: |
        python3 --version
        which python3
        
    - name: Install dependencies (Mac)
      run: |
        # Install using Homebrew instead of apt-get
        brew install mysql redis node
        
    - name: Install frappe-bench
      run: |
        python3 -m pip install --user frappe-bench
        
    - name: Start services (Mac)
      run: |
        # Start services using brew instead of systemctl
        brew services start mysql
        brew services start redis
        
        # Wait for MySQL to start
        sleep 10
        
        # Setup MySQL (Mac doesn't require sudo for mysql command)
        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';" || echo "MySQL setup may have failed"
        mysql -u root -ppassword -e "FLUSH PRIVILEGES;" || echo "MySQL flush may have failed"
        
    - name: Create ERPNext site
      run: |
        cd $HOME
        
        # Initialize bench
        bench init --frappe-branch develop --python python3 frappe-bench
        cd frappe-bench
        
        # Get ERPNext
        bench get-app --branch develop https://github.com/frappe/erpnext.git
        
        # Create site
        bench new-site test-site --admin-password admin --mariadb-root-password password
        
        # Install ERPNext
        bench --site test-site install-app erpnext
        
    - name: Start ERPNext
      run: |
        cd $HOME/frappe-bench
        
        # Start in background
        nohup bench start > bench.log 2>&1 &
        sleep 30
        
        # Test if site is running
        curl -f http://localhost:8000 || echo "Site not ready yet"
        
    - name: Show site info
      run: |
        cd $HOME/frappe-bench
        bench --site test-site list-apps
        
        # Show some logs
        echo "Recent logs:"
        tail -20 bench.log || echo "No logs found"
