name: Local ERPNext Deploy

on:
  push:
    branches: 
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main

jobs:
  deploy-local:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip python3-venv
        sudo apt-get install -y mariadb-server redis-server
        sudo apt-get install -y nodejs npm
        sudo npm install -g yarn

    - name: Install frappe-bench
      run: |
        pip install frappe-bench

    - name: Start services
      run: |
        sudo systemctl start mariadb
        sudo systemctl start redis-server
        
        # Setup MariaDB
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"
        sudo mysql -u root -ppassword -e "FLUSH PRIVILEGES;"

    - name: Create ERPNext site
      run: |
        # Initialize bench
        bench init --frappe-branch develop --python python3 frappe-bench
        cd frappe-bench
        
        # Get ERPNext
        bench get-app --branch develop https://github.com/frappe/erpnext.git
        
        # Create site
        bench new-site test-site --admin-password admin --mariadb-root-password password
        
        # Install ERPNext
        bench --site test-site install-app erpnext

    - name: Start ERPNext
      run: |
        cd frappe-bench
        bench start &
        sleep 30
        
        # Test if site is running
        curl -f http://localhost:8000 || echo "Site not ready yet"

    - name: Show site info
      run: |
        cd frappe-bench
        bench --site test-site list-apps
