name: Simple ERPNext Deploy

on:
  push:
    branches: 
      - main
      - staging
      - develop
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install and setup everything
      run: |
        # Install services
        arch -arm64 brew install mysql redis node || echo "Some packages already installed"
        
        # Start services
        arch -arm64 brew services start mysql
        arch -arm64 brew services start redis
        sleep 15
        
        # Setup MySQL
        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';" 2>/dev/null || echo "MySQL already configured"
        
        # Install frappe-bench using --user flag (safe method)
        pip3 install --user frappe-bench
        
        # Add to PATH
        export PATH="$HOME/.local/bin:$PATH"
        
        # Go to home directory
        cd $HOME
        rm -rf frappe-bench
        
        # Create ERPNext site
        $HOME/.local/bin/bench init --frappe-branch develop --python python3 frappe-bench
        cd frappe-bench
        $HOME/.local/bin/bench get-app --branch develop https://github.com/frappe/erpnext.git
        $HOME/.local/bin/bench new-site test-site --admin-password admin --mariadb-root-password password
        $HOME/.local/bin/bench --site test-site install-app erpnext
        
        # Start ERPNext in background
        nohup $HOME/.local/bin/bench start > bench.log 2>&1 &
        
        echo "ERPNext is starting... Please wait 60 seconds then check http://localhost:8000"
