name: ERPNext Docker Deploy

on:
  push:
    branches: 
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:    

jobs:
  deploy-docker:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create docker-compose.yml
      run: |
        cat > docker-compose.yml << 'EOF'
        version: '3.8'
        
        services:
          db:
            image: mariadb:10.6
            environment:
              MYSQL_ROOT_PASSWORD: admin
              MYSQL_DATABASE: erpnext
            ports:
              - "3306:3306"
            volumes:
              - db_data:/var/lib/mysql
          
          redis:
            image: redis:alpine
            ports:
              - "6379:6379"
          
          erpnext:
            image: frappe/erpnext:latest
            ports:
              - "8000:8000"
            environment:
              DB_HOST: db
              DB_ROOT_USER: root
              DB_ROOT_PASSWORD: admin
              REDIS_CACHE: redis:6379
              REDIS_QUEUE: redis:6379
            depends_on:
              - db
              - redis
        
        volumes:
          db_data:
        EOF

    - name: Stop existing containers
      run: |
        docker-compose down -v || echo "No existing containers"

    - name: Start ERPNext
      run: |
        docker-compose up -d
        
        echo "Waiting for ERPNext to start..."
        sleep 60

    - name: Check status
      run: |
        docker-compose ps
        
        echo ""
        echo "ERPNext should be available at: http://localhost:8000"
        echo "Default credentials: Administrator / admin"
        
        # Show logs
        echo ""
        echo "=== ERPNext Logs ==="
        docker-compose logs erpnext --tail=20
