name: Deploy ERPNext

on:
  push:
    branches: 
      - main
      - staging
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install frappe-bench
      run: |
        pip install frappe-bench

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Connect to EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy using Helm
      run: |
        # Add Frappe Helm repository
        helm repo add frappe https://helm.erpnext.com
        helm repo update
        
        # Deploy ERPNext
        helm upgrade --install erpnext frappe/erpnext \
          --namespace erpnext \
          --create-namespace \
          --set image.repository=frappe/erpnext \
          --set image.tag=latest \
          --wait

    - name: Verify deployment
      run: |
        kubectl get all -n erpnext
