name: ERPNext Docker Deploy

on:
  push:
    branches: 
      - main
      - staging
      - develop
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy ERPNext Stack
      run: |
        # Create docker-compose file
        cat > docker-compose.yml << 'EOF'
        version: '3.7'

        services:
          db:
            image: mariadb:10.6
            command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --skip-innodb-read-only-compressed
            environment:
              MYSQL_ROOT_PASSWORD: 123
            volumes:
              - db-data:/var/lib/mysql

          redis:
            image: redis:6.2-alpine

          erpnext:
            image: frappe/erpnext:latest
            deploy:
              restart_policy:
                condition: on-failure
            ports:
              - "8000:8000"
            volumes:
              - sites:/home/frappe/frappe-bench/sites
            depends_on:
              - db
              - redis

          configurator:
            image: frappe/erpnext:latest
            deploy:
              restart_policy:
                condition: none
            entrypoint:
              - bash
              - -c
            command:
              - >
                ls -1 apps > sites/apps.txt;
                bench set-config -g db_host db;
                bench set-config -g redis_cache redis:6379;
                bench set-config -g redis_queue redis:6379;
                bench set-config -g redis_socketio redis:6379;
                bench new-site frontend --no-mariadb-socket --admin-password=admin --db-root-password=123;
                bench --site frontend install-app erpnext;
                bench --site frontend enable-scheduler;
                bench --site frontend set-maintenance-mode off;
            depends_on:
              - db
              - redis
            volumes:
              - sites:/home/frappe/frappe-bench/sites

        volumes:
          sites:
          db-data:
        EOF

        # Deploy the stack
        docker-compose down -v
        docker-compose up -d

    - name: Wait and verify
      run: |
        echo "⏳ Waiting for ERPNext to initialize..."
        sleep 90
        
        # Check if containers are running
        docker-compose ps
        
        echo ""
        echo "🎉 ERPNext should be ready!"
        echo "🌐 URL: http://localhost:8000"
        echo "👤 Username: Administrator"
        echo "🔑 Password: admin"
        
        # Test if it's responding
        curl -f http://localhost:8000 > /dev/null 2>&1 && echo "✅ ERPNext is responding!" || echo "⚠️ ERPNext might still be starting..."
