name: Local ERPNext Deploy

on:
  push:
    branches: 
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:    

jobs:
  deploy-local:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install frappe-bench
      run: |
        python3 -m pip install --user frappe-bench
        
    - name: Start services (if not running)
      run: |
        # Check and start MySQL if needed
        if ! brew services list | grep -q "mysql.*started"; then
          arch -arm64 brew services start mysql
        fi
        
        # Check and start Redis if needed  
        if ! brew services list | grep -q "redis.*started"; then
          arch -arm64 brew services start redis
        fi
        
        # Wait for services
        sleep 10
        
    - name: Setup MySQL (if needed)
      run: |
        # Try to setup MySQL password (ignore if already set)
        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';" 2>/dev/null || echo "MySQL already configured"
        mysql -u root -ppassword -e "FLUSH PRIVILEGES;" 2>/dev/null || echo "MySQL flush completed"
        
    - name: Create ERPNext site
      run: |
        cd $HOME
        
        # Remove existing bench if it exists (for clean runs)
        rm -rf frappe-bench
        
        # Initialize bench
        ~/.local/bin/bench init --frappe-branch develop --python python3 frappe-bench
        cd frappe-bench
        
        # Get ERPNext
        ~/.local/bin/bench get-app --branch develop https://github.com/frappe/erpnext.git
        
        # Create site
        ~/.local/bin/bench new-site test-site --admin-password admin --mariadb-root-password password
        
        # Install ERPNext
        ~/.local/bin/bench --site test-site install-app erpnext
        
    - name: Start ERPNext
      run: |
        cd $HOME/frappe-bench
        
        # Start in background
        nohup ~/.local/bin/bench start > bench.log 2>&1 &
        sleep 45
        
        # Test if site is running
        curl -f http://localhost:8000 || echo "Site not ready yet, check logs"
        
    - name: Show site info
      run: |
        cd $HOME/frappe-bench
        ~/.local/bin/bench --site test-site list-apps
        
        # Show logs
        echo "=== Recent logs ==="
        tail -30 bench.log || echo "No logs found"
